### ISSUE TITLE
WebSocket disconnects immediately

### ISSUE THREAD

**Issue by nikhil191090** [tkmn0/SimpleWebRTCExample_iOS#13]
Hello,

First of all thanks a lot for your project! It helped us a lot. But I am facing WebSocket disconnect issue as soon as I launch the app. Please help, I am kind of stuck here from days

**Comment by saroar** [comment]
yes this is the way this app work WebSocket will connect again when after you end a call so if you want to WebSocket  disconnect  immediately check code and remove that 
best of luck

**Comment by tkmn0** [comment]
Hi, thanks guys for opening issue and commented :)

>  But I am facing WebSocket disconnect issue as soon as I launch the app    

Did you run websocket server at your computer? 
If no, check [usage]( https://github.com/tkmn0/SimpleWebRTCExample_iOS#usage). 
Then, adjust IP Address to your case.

Please let me know if you have any questions.
