### ISSUE TITLE
Crash on call button , after web socket connected

### ISSUE THREAD

**Issue by FaizalMalik** [tkmn0/SimpleWebRTCExample_iOS#14]
Thanks for the code.! 

I am able to run the code and run on my device and simulator. Everything works fine up to connect. 

After that, When I click call button on the phone, the simulator will crash and throwing an error 

No factory registered for id <CFUUID 0x60000093ff20> F8BB1C28-BAE8-11D6-9C31-00039315CD46
succeed to set local answer SDP

![Simulator Screen Shot - iPhone 11 - 2020-01-17 at 20 01 41](https://user-images.githubusercontent.com/32692684/72619915-5263b380-3964-11ea-8db2-793280c8a9e7.png)
<img width="1274" alt="Screen Shot 2020-01-17 at 8 02 01 PM" src="https://user-images.githubusercontent.com/32692684/72619922-57286780-3964-11ea-9686-9757f3f56379.png">

**Comment by tkmn0** [comment]
Hi, Thanks for opening this issue :)

I will check it within a few days.
Could you tell me your environment ?
(e.g. iOS version, iPhone version,  and so on)

**Comment by FaizalMalik** [comment]
@tkmn0  iOs version 13.3, simulator iphone 11
                 iOs version 13.3, iPhone 8plus 
                 Xcode 11.3

Also, I would like to know, whether the audio and video work fine with this configuration? 
because I couldn't run and check the audio streaming.. due to this issue ..!

**Comment by tkmn0** [comment]
HI, I'm sorry for the late replay.
Actually, still I don't have any solution.

I guess this is WebRTC.framework bug for simulator.
(coz there are some log outputs and issues, [RTCPixelbuffer](https://stackoverflow.com/questions/55372078/class-rtccvpixelbuffer-is-implemented-in-both-one-of-the-two-will-be-used-whic), [AudioPlayer](https://stackoverflow.com/questions/58313375/thread-1-exc-bad-access-code-1-address-0x48-avaudiofoundation))

So, I will update framework and try again.

**Comment by FaizalMalik** [comment]
@tkmn0  Suppose if I run the code successfully, will it transfer the audio as well as video on other side ?

I am asking this question, As I couldn't run the app ! (I have only one iPhone).

**Comment by tkmn0** [comment]
> Suppose if I run the code successfully, will it transfer the audio as well as video on other side ?

Yes it will :) 
This code is example for audio, video, and data bidirectional transmission with WebRTC.

**Comment by nkllkc** [comment]
Is there any change on this? :) Thank you!

**Comment by tkmn0** [comment]
@nkllkc 
Not yet. Thanks :)

**Comment by gnik2036** [comment]
Is there any change on this?  it still make a big issue  :( Thank you!

**Comment by tkmn0** [comment]
Hi :)
Unfortunately, not yet.
However, if You want to establish connection between simulator and iPhone right now, You can try to update frame work.

By the way, I think it's better to use [this pod](https://cocoapods.org/pods/GoogleWebRTC).
So, first, I will update current Framework version, second, I will change to use the GoogleWebRTC pod.

**Comment by tkmn0** [comment]
Hey guys. 
Last weekend, I rebuild WebRTC.framework and tried to connect simulator and my iPhone.
In the iPhone side, it was fine, but in the simulator side,  the remote video view rendered red screen.

According to [this post](https://stackoverflow.com/questions/58205421/webrtc-ios-13-simulator-red-screen-h264-decoding), this is WebRTC.framework side bug. 

Instead of WebRTC.framework, I'm planning to use SFSafariView + web page for simulator. (I'm not sure this is a good way or not for simulator).

**Comment by tkmn0** [comment]
1. updated framework.
2. use vp8 or vp9 codec for simulator

I already merged it to master. :)
