### ISSUE TITLE
sounds coming from handset, how can i change to speaker ?

### ISSUE THREAD

**Issue by emirbeytekin** [tkmn0/SimpleWebRTCExample_iOS#15]
sounds coming from handset, how can i change to speaker ?

**Comment by tkmn0** [comment]
Hi :)
How about [this](https://stackoverflow.com/a/50753160)?
(I want to research, but currently I don't have enough time...)

**Comment by emirbeytekin** [comment]
good idea but i found a new easy way, thank for response :)
