### ISSUE TITLE
Server side websocket is not connected

### ISSUE THREAD

**Issue by venkatmacapp** [tkmn0/SimpleWebRTCExample_iOS#17]
Thanks for the good work. In local host worked perfectly. But i tried to move live server websocket is not connected. So please guide me the installation from server.

**Comment by tkmn0** [comment]
Hi, thank you for your question.

I have some a question.
What service did you use to run server app? (ex: ec2, gcp, heroku, now, glitch ?)

If you use ec2 or gcp, check your security group and tcp ports. 
Currently, example signaling server uses 8080, so please open 8080 port for server.

**Comment by venkatmacapp** [comment]
Hi tkmn0,
Thank you for your quick reply.
I am using ec2 Server. I ll check and let u know.

**Comment by venkatmacapp** [comment]
Thanks thmn0 it's worked
