### ISSUE TITLE
I want to implement AppRTC on your example it is possible? 

### ISSUE THREAD

**Issue by Rylaa** [tkmn0/SimpleWebRTCExample_iOS#19]
Hi, thanks for the project looking very helpful. I have a few question.
 i don't want use socket. I want this; User create a room on AppRTC(https://appr.tc/) and second user joins this room with room id. Your example supports only web socket?

**Comment by tkmn0** [comment]
Hi, I'm glad to hear that this project is helpful for you.

I think AppRTC uses [websocket server written in golang](https://github.com/webrtc/apprtc/tree/master/src/collider) .

> Your example supports only web socket? 

Yes it is.
This repository includes super simple signaling server written in node.js. 
You can create your own signaling server, or you may customize this client to connect AppRTC signaling server :)

**Comment by Rylaa** [comment]
Thanks for reply.
I'm using AppRTC signaling server. I want to connect a AppRTC room on iPhone. I don't know how to connect the room and get fetch image and I didin't find any example on AppRTC. So I can convert your WebRTC example? this possible?

**Comment by tkmn0** [comment]
I see. 
I'm not sure this repository can connect to AppRTC signaling server...
I hope [this project](https://github.com/ISBX/apprtc-ios) is helpful for your case.
