### ISSUE TITLE
Simple and powerful code :) 

### ISSUE THREAD

**Issue by saroar** [tkmn0/SimpleWebRTCExample_iOS#2]
hi try it but does work sound? do you know why?
I am using this pod  > 'GoogleWebRTC', '=1.1.24717' is that reason the audio sound does not work?
do you know also who to work with callKit and PushKit?
thanks for code

**Comment by tkmn0** [comment]
Thanks for reading my code & throwing your star on this repository :) 

> I am using this pod > 'GoogleWebRTC', '=1.1.24717' is that reason the audio sound does not work?    

I think you are correct.  
The WebRTC API may be different from that version.
When I have  time to check, I will try with that library not with my pre build framework.

> do you know also who to work with callKit and PushKit?

Unfortunately, No, I don't.

Thanks!

**Comment by tkmn0** [comment]
I will check it.
Could you tell me your environment? (simulator & simulator ?)

**Comment by saroar** [comment]
simulator & iPhone 6

**Comment by tkmn0** [comment]
hi 
I checked in my environment. (simulator & iPhone6)
Actually, the volume was too soft, so I increased the remote audio track ([check it out](https://github.com/tkmn0/SimpleWebRTCExample_iOS/blob/master/SimpleWebRTC/WebRTC/WebRTCClient.swift#L410)).  

In addition, RTCFileVideoCapturer does not capture audio from mp4 file BUT captures mic audio.
So, please allow to use mic on your PC when you run simulator.

**Comment by saroar** [comment]
@tkmn0 can we make it default max volume?

**Comment by saroar** [comment]
Hi everything is working fine after restart my mac thanks and sorry
