### ISSUE TITLE
fix data channel

### ISSUE THREAD

**Issue by tkmn0** [tkmn0/SimpleWebRTCExample_iOS#21]
Currently, data channel does not establish connection.

**Comment by lasernite** [comment]
Any hunches or hypotheses about where/what the bug might be that's making the data channel fail? Thanks!

**Comment by tkmn0** [comment]
Hi thanks.
I'm not sure the cause of bug. Now, I just found the data channel is not working.
I will check this issue :) Thanks again.

**Comment by lasernite** [comment]
Thanks so much! This project is super cool. Please let me know if you find anything :)

**Comment by tkmn0** [comment]
@lasernite 
Hi, I checked data channel and it works well without any changes. I think some other problem affected to data channel.
I think, you can check data channel in your environment. :)

**Comment by tkmn0** [comment]
@lasernite 
fixed :)

**Comment by lasernite** [comment]
Yay! :D Just played with it and is perfect! Thank you!
