### ISSUE TITLE
I cloned the project but it saying WebSocket is disconnected

### ISSUE THREAD

**Issue by AnkurLahiry** [tkmn0/SimpleWebRTCExample_iOS#22]
Hi, 

Thanks for the project. I did everything which is described In Readme. After successfully add the WebSocket framework, I ran the app saying WebSocket is disconnected. Am I missing something?

**Comment by tkmn0** [comment]
Hi, thank you for your question.

1. Did you connect your iPhone and your PC (signaling server running) to same network (LAN)?
2. Did you change [here](https://github.com/tkmn0/SimpleWebRTCExample_iOS/blob/master/SimpleWebRTC/ViewController/ViewController.swift#L41) to your case?

Best regards.

**Comment by AnkurLahiry** [comment]
Yes!

Solved my problem, the problem was step 2.  Please add this in Readme. 

I loved this project.

**Comment by tkmn0** [comment]
I'm sorry, 
I will add step 2 to README.
Anyway, I'm glad to hair to solve you problem.

Thanks! If you don't mind, give star to this project :)

**Comment by AnkurLahiry** [comment]
Sure, already did that

`data channel is not ready state`

How to solve it?

**Comment by tkmn0** [comment]
Thanks :)

> data channel is not ready state    

Currently, this project has data channel problem (#21).
I will check this problem later.

Did you tap call button? 
If so, signaling will start and connection will establish. What is in your xcode console?
