### ISSUE TITLE
can this example run multiples devices at once ? 

### ISSUE THREAD

**Issue by guns28** [tkmn0/SimpleWebRTCExample_iOS#23]
Hi , thank you for this project it saved me a lot of time, 
i'm trying to run the example on 3 iphones to make a streaming but there only 2 that can communicate at the same time, can we make an update to make it like a chat room where they all connect to the same room to chat ?
if you just can confirm me and just give me an idea i'm still reading and trying to understand the code and how the whole application is working.
Best regards

**Comment by tkmn0** [comment]
Hi, I'm glad to hair this project is somehow helpful for you.

Currently, this project can establish only peer to peer connection( totally, 2 devices ).

>  can we make an update to make it like a chat room where they all connect to the same room to chat ?

Sound good :) 
I think there are two way to create like a chat room.
1. Full mesh connection way (only needs signaling server)
2. SFU (Selecting Forward Unit) connection way (needs signaling and  media server)    

If you are not familiar with those ways, [see here](https://medium.com/@khan_honney/webrtc-servers-and-multi-party-communication-in-webrtc-6bf3870b15eb).

I have another example for sfu server ([here](https://github.com/tkmn0/medooze-sfu-typescript)).
I think the first way is easy but high performance will be needed in client side, and I think the second way is good for client but it needs to maintain server side.

**Comment by tkmn0** [comment]
I think the first one I mean, full mesh way is better for this repository.
If I could run a simple full-mesh signaling server on heroku, it will be helpful developers :)

**Comment by guns28** [comment]
Thank you for your response i will check it and get back to you if i need any help if you don't mind. best

**Comment by guns28** [comment]
Do you have any useful link that helped you write this code i need to understand it more so i can handle the changes. thx

**Comment by tkmn0** [comment]
> Do you have any useful link that helped you write this code
- Maybe you know this [great example](https://github.com/stasel/WebRTC-iOS)
- [Official objctive-c sdk](https://webrtc.googlesource.com/src/+/refs/heads/master/sdk/objc)
- [GitHub - nakadoribooks/webrtc-ios: webrtc-ios](https://github.com/nakadoribooks/webrtc-ios)

In addition, I think webrtc connection flow is same for each platforms(web, android, ios, c++). So, other language examples are also helpful :) (The api is similar too).

**Comment by guns28** [comment]
thx man , all my respect.
