### ISSUE TITLE
Mix call audio with locally playing video

### ISSUE THREAD

**Issue by 9SL9** [tkmn0/SimpleWebRTCExample_iOS#25]
The more I look through your code and the project the more I love it!

Quick question - is it possible to mix the audio of the caller with a locally playing video (AVPlayer)?

Thanks again

**Comment by tkmn0** [comment]
Thank you so much :) 
I'm sorry, I'm not familiar with audio mixing with WebRTC.

WebRTC can handle multiple media tracks so, I think you can add your audio tracks to media stream.

Best Regards.

**Comment by 9SL9** [comment]
Thanks
