### ISSUE TITLE
change camera position?

### ISSUE THREAD

**Issue by emirbeytekin** [tkmn0/SimpleWebRTCExample_iOS#26]
hello,
how can i change my camera position on connected to server ?

**Comment by tkmn0** [comment]
Hi,
Currently, this project can not swap camera (front only).
But you can add custom camera swapping, I think.

**Comment by emirbeytekin** [comment]
Yes, i'm added on WebRTCClient.swift setup function but if i want change camera, app is freezing on front camera

```
if self.channels.video {
            if isFront {
                self.localVideoTrack.remove(self.localRenderView!)
                startCaptureLocalVideo(cameraPositon: .front, videoWidth: 640, videoHeight: 640, videoFps: 30)
            } else {
                self.localVideoTrack.remove(self.localRenderView!)
                startCaptureLocalVideo(cameraPositon: .back, videoWidth: 640, videoHeight: 640, videoFps: 30)
            }
            self.localVideoTrack?.add(self.localRenderView!)
        }
```

**Comment by emirbeytekin** [comment]
Anyone help me ?

**Comment by tkmn0** [comment]
Hi, Sorry for the late reply.
I implemented camera switch function on master branch.
You can switch camera position with tapping local camera view. 
Check it out :)

I think you just need to stop capture first.
Thank you for your question!
