### ISSUE TITLE
How can i add room key and user key for websocket connection?

### ISSUE THREAD

**Issue by orkunaryus** [tkmn0/SimpleWebRTCExample_iOS#27]
Hi, I am trying to connect to an existing web server. I need to enter the user key and room key for websocket. How can I add?

**Comment by tkmn0** [comment]
Hi, Sorry for the late reply. I have a question. Can I ask about the existing web server in detail? Do you mean you want to add room key and user key for [this server app](https://github.com/tkmn0/SimpleWebRTCExample_iOS/tree/master/SignalingServer)?

**Comment by tauypaldiyev** [comment]
@tkmn0 Hi!) Help please, I want to call to exact user, for this I have user id/key and room id/key. Now, where to enter them? In other words, how can I call to user B from users [A, B, C, D, E, ...]?
