### ISSUE TITLE
Is it possible to change this for multiple clients?

### ISSUE THREAD

**Issue by lygon55555** [tkmn0/SimpleWebRTCExample_iOS#29]
Hi!
This project is really awesome.
Code is very clean, nice and working very well 😀
For now, this project allows only 2 clients.
Is it possible to change this for multiple clients?

**Comment by tkmn0** [comment]
Hi, thank you for your awesome comment and question :)

Actually, I'm working on webrtc full-mesh connection library named Peers. Now, Peers is done for server and web client with vue.js but not public repository. I'm ready for documents. I'm planning to publish Peers in early August. 
After I publish Peers, I will make example of Peers implementation in this project.
If you want to know about WebRTC connection topology, refer [here](https://medium.com/@khan_honney/webrtc-servers-and-multi-party-communication-in-webrtc-6bf3870b15eb)

After I created example fo Peers implementation, I will try to create SFU server and example client of that server. However, in this case, I'm not sure when I will work on it.
Thanks.

**Comment by lygon55555** [comment]
Oh, I See.
Actually, I'm also working on WebRTC connection for multiple peers.
As an iOS developer, it's kind of difficult but I'm having fun with it.
I'd love to contribute if you publish Peers!
Thank you so much for your comment ✋
