### ISSUE TITLE
Hello ! Thanks for your project, little questions here ! 

### ISSUE THREAD

**Issue by Suriteka** [tkmn0/SimpleWebRTCExample_iOS#3]
Hello,

First of all thanks a lot for your project ! It helped us a lot, we are touching WebRTC for the first time !
But I have some questions, we actually have a drone (DJI Spark) and we have a Data (Array Buffer) variable.

We have the websocket server, and we actually did a call with your source code. 🔥

So we have something like this 
``` 
func videoFeed(_ videoFeed: DJIVideoFeed, didUpdateVideoData videoData: Data) {
        if !webRTCClient.isConnected {
            webRTCClient.connect(onSuccess: { (offerSDP: RTCSessionDescription) -> Void in
                self.sendSDP(sessionDescription: offerSDP)
            })
        }

        videoData.withUnsafeBytes { (bytes:UnsafePointer<UInt8>) in
           videoPreview?.push(UnsafeMutablePointer(mutating: bytes), length: Int32(videoData.count))
        }
}
 ```

But during the init of WebRTC, You are doing the creation of videoPreview with setupDataChannel. How can I change this to my videoData my videoSource with another source ?

Arigato gozaimasu ! 
(Trying to learn some nihongo )

**Comment by tkmn0** [comment]
hi !
I create RTCCustomFrameCapturer class.
This class can create video source from CMSampleBuffer.

Actually, I tried to create video source from CVPixelBuffer so that you can create video source from data (or bytes?) but, I found we need CMSampleBuffer to create RTCVideoFrame coz RTCVideoFrame requires time stamp.

**Comment by Suriteka** [comment]
Hi thanks a lot for your answer ! 👍 

We are trying your solutions right now.
Actually we are using ```webRTCClient.sendData(data: videoData)``` and it works pretty great ! 
But we will try with your class too. Thanks a lot. ❤️

**Comment by tkmn0** [comment]
Great!! 
It's my pleasure haha :)

https://github.com/tkmn0/webrtc_sample is JUST SAMPLE javascript API for WebRTC on browser but does not hove html.
Actually, now I'm trying to create browser side simple WebRTC example written in typescript.
However, I don't have enough time.

If you create socket connection & viewer side (html) you can connect iOS and web browser each other( I recommend with chrome).

**Comment by Suriteka** [comment]
Ok I see.

I actually have a socket connection between my browser (client) and my server. Just need to send the good SDP and get the SDP of the drone. And then show the video. But thanks a lot for your help. 😄 

Have a good day in Japan. (Would love to go once in my life 🗾)

**Comment by tkmn0** [comment]
Sounds good! 👍 

I'm looking forward to your project 😁

You too in France:)  
Let's meet up if you came to japan.
