### ISSUE TITLE
Can you give me any advice on implementing webrtc on macos?

### ISSUE THREAD

**Issue by SooChang-Lee** [tkmn0/SimpleWebRTCExample_iOS#34]
Hi~

I think this is a good project for ios webrtc development.

I want to implement webrtc on osx platform.

Can you give me any advice for implementing webrtc in osx?

Thank you.

**Comment by tkmn0** [comment]
HI! 
Thank you for your comment :)
Unfortunately, I don't have enough knowledge for osx development.

I guess there are two steps.

1. We need to build WebRTC SDK for osx.
- [official](https://webrtc.github.io/webrtc-org/native-code/development/)
- [my memo (for iOS)](https://github.com/tkmn0/SimpleWebRTCExample_iOS/blob/master/docs/BuildWebRTCFrameworkFlow.md)

2. We can code with WebRTC SDK on XCode. But I do not know how to for osx...

Thank you.
