### ISSUE TITLE
Storyboard!

### ISSUE THREAD

**Issue by saroar** [tkmn0/SimpleWebRTCExample_iOS#4]
How I can use your project with storyboard I am not familiar with create view with code :( 
98% your code :) https://github.com/saroar/WebRTCBeta.git but trying to add storyboard but can't see remote user video :( could you please help a little bit 
this git use same signal server as your git use

**Comment by tkmn0** [comment]
I didn't use storyboard and I thought everyone can run this project with copy & paste like without storyboard :)

Anyway, I'm glad to hear you are trying to add storyboard to your git.
I will try to run your project.

**Comment by saroar** [comment]
I run follow your code and update it :) 
![simulator screen shot - iphone x - 2019-02-09 at 14 27 13](https://user-images.githubusercontent.com/8770772/52520123-ec13e280-2c76-11e9-9bdf-7d8f34a53bdd.png)
its still like demo but i will update you my final version and my final version app :) which will be on AppStore :)

**Comment by tkmn0** [comment]
Awesome!  👏
I'm looking forward to see your app on AppStore :)

> also, do you know who to make a better video quality?

I think you can set video width from here: https://github.com/tkmn0/SimpleWebRTCExample_iOS/blob/master/SimpleWebRTC/WebRTC/WebRTCClient.swift#L251.
If you use RTCCustomFrameCapturer, you can set preset from here: https://github.com/tkmn0/SimpleWebRTCExample_iOS/blob/master/SimpleWebRTC/CameraSession/CameraSession.swift#L43.

However, In my opinion, WebRTC cannot handle too large size video (e.g. 3840x2160).

**Comment by saroar** [comment]
#### I think you can set video width from here:
you mean here https://github.com/tkmn0/SimpleWebRTCExample_iOS/blob/master/SimpleWebRTC/WebRTC/WebRTCClient.swift#L76 yes
