### ISSUE TITLE
Voice Issue

### ISSUE THREAD

**Issue by saroar** [tkmn0/SimpleWebRTCExample_iOS#5]
Did you notice when you talk from iPhone you listen to your own voice? i just notice when i was trying to voice all only

**Comment by tkmn0** [comment]
HI :) 
Sorry for replying so late.

I checked iPhone6 & iPhoneXR with audio only situation.
In addition, I put iPhoneXR enough far place, so, I didn't notice my own voice...

**Comment by saroar** [comment]
NO need to sorry thanks for reply :) maybe i get this issue becz i use MacBook and iPhone :)
