### ISSUE TITLE
May I know when we need to use it?

### ISSUE THREAD

**Issue by saroar** [tkmn0/SimpleWebRTCExample_iOS#9]
https://github.com/tkmn0/SimpleWebRTCExample_iOS/blob/fbf991b6be6188163e3106047065f74addf72859/SimpleWebRTC/ViewController/ViewController.swift#L65

and how it helps our webRTC app video quality

**Comment by tkmn0** [comment]
If useCustomCapturer is true, you can send custom video image. (e.g. CIFilter, OpenCV and so on.)

So, it does not help video quality but accept custom video image which edited pixels with some frameworks.
